apiVersion: v1
kind: Service
metadata:
  name: calculatrice-service
spec:
  type: NodePort
  selector:
    app: calculatrice
  ports:
    - protocol: TCP
      port: 8000       # port externe
      targetPort: 5000 # port container
