apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistique
  template:
    metadata:
      labels:
        app: statistique
    spec:
      containers:
      - name: statistique
        image: statistiques:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: statistique
spec:
  type: NodePort
  selector:
    app: statistique
  ports:
    - port: 8080        # port interne du service
      targetPort: 8080  # port du container Flask
      nodePort: 30400   # port externe accessible depuis l’extérieur
